export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const ERROR_IN_PRODUCT_LIST = 'ERROR_IN_PRODUCT_LIST';
export const CLEAR_PRODUCT_LIST = 'CLEAR_PRODUCT_LIST';

export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const ERROR_IN_PRODUCT_DETAILS = 'ERROR_IN_PRODUCT_DETAILS';
export const CLEAR_PRODUCT_DETAILS = 'CLEAR_PRODUCT_DETAILS';